/*
 * Created on 18 ÎåÔÂ 2015 ( Time 10:36:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mmm.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Student implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer age;

    @NotNull
    @Size( min = 1, max = 20 )
    private String name;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAge( Integer age ) {
        this.age = age;
    }
    public Integer getAge() {
        return this.age;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(age);
        sb.append("|");
        sb.append(name);
        return sb.toString(); 
    } 


}
