/*
 * Created on 18 ÎåÔÂ 2015 ( Time 10:36:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.mmm.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class SysUser implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 32 )
    private String sysId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 100 )
    private String userName;

    @Size( max = 100 )
    private String userPassword;


    private Boolean passwordNeedsReset;

    @Size( max = 3 )
    private String preferredLanguage;

    @Size( max = 3 )
    private String country;

    @Size( max = 40 )
    private String introduction;

    @Size( max = 50 )
    private String firstName;

    @Size( max = 50 )
    private String middleName;

    @Size( max = 50 )
    private String lastName;

    @Size( max = 151 )
    private String name;

    @Size( max = 40 )
    private String phone;

    @Size( max = 40 )
    private String homePhone;

    @Size( max = 40 )
    private String mobilePhone;

    @Size( max = 100 )
    private String email;

    @Size( max = 60 )
    private String title;

    @Size( max = 40 )
    private String gender;


    private Date lastLoginTime;


    private Boolean lockedOut;

    @Size( max = 40 )
    private String lastPassword;

    @Size( max = 32 )
    private String manager;

    @Size( max = 100 )
    private String photo;

    @Size( max = 32 )
    private String department;

    @Size( max = 32 )
    private String company;

    @Size( max = 255 )
    private String street;

    @Size( max = 40 )
    private String city;

    @Size( max = 40 )
    private String state;

    @Size( max = 40 )
    private String zip;


    private Boolean vip;

    @Size( max = 32 )
    private String building;


    private Integer failedAttempts;


    private Boolean active;

    @Size( max = 32 )
    private String sysDomain;

    @Size( max = 32 )
    private String costCenter;

    @Size( max = 40 )
    private String sysUpdatedBy;


    private Date sysUpdatedOn;

    @Size( max = 40 )
    private String sysCreatedBy;


    private Date sysCreatedOn;

    @Size( max = 80 )
    private String sysClassName;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSysId( String sysId ) {
        this.sysId = sysId ;
    }

    public String getSysId() {
        return this.sysId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserName( String userName ) {
        this.userName = userName;
    }
    public String getUserName() {
        return this.userName;
    }

    public void setUserPassword( String userPassword ) {
        this.userPassword = userPassword;
    }
    public String getUserPassword() {
        return this.userPassword;
    }

    public void setPasswordNeedsReset( Boolean passwordNeedsReset ) {
        this.passwordNeedsReset = passwordNeedsReset;
    }
    public Boolean getPasswordNeedsReset() {
        return this.passwordNeedsReset;
    }

    public void setPreferredLanguage( String preferredLanguage ) {
        this.preferredLanguage = preferredLanguage;
    }
    public String getPreferredLanguage() {
        return this.preferredLanguage;
    }

    public void setCountry( String country ) {
        this.country = country;
    }
    public String getCountry() {
        return this.country;
    }

    public void setIntroduction( String introduction ) {
        this.introduction = introduction;
    }
    public String getIntroduction() {
        return this.introduction;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }
    public String getFirstName() {
        return this.firstName;
    }

    public void setMiddleName( String middleName ) {
        this.middleName = middleName;
    }
    public String getMiddleName() {
        return this.middleName;
    }

    public void setLastName( String lastName ) {
        this.lastName = lastName;
    }
    public String getLastName() {
        return this.lastName;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setHomePhone( String homePhone ) {
        this.homePhone = homePhone;
    }
    public String getHomePhone() {
        return this.homePhone;
    }

    public void setMobilePhone( String mobilePhone ) {
        this.mobilePhone = mobilePhone;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setGender( String gender ) {
        this.gender = gender;
    }
    public String getGender() {
        return this.gender;
    }

    public void setLastLoginTime( Date lastLoginTime ) {
        this.lastLoginTime = lastLoginTime;
    }
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    public void setLockedOut( Boolean lockedOut ) {
        this.lockedOut = lockedOut;
    }
    public Boolean getLockedOut() {
        return this.lockedOut;
    }

    public void setLastPassword( String lastPassword ) {
        this.lastPassword = lastPassword;
    }
    public String getLastPassword() {
        return this.lastPassword;
    }

    public void setManager( String manager ) {
        this.manager = manager;
    }
    public String getManager() {
        return this.manager;
    }

    public void setPhoto( String photo ) {
        this.photo = photo;
    }
    public String getPhoto() {
        return this.photo;
    }

    public void setDepartment( String department ) {
        this.department = department;
    }
    public String getDepartment() {
        return this.department;
    }

    public void setCompany( String company ) {
        this.company = company;
    }
    public String getCompany() {
        return this.company;
    }

    public void setStreet( String street ) {
        this.street = street;
    }
    public String getStreet() {
        return this.street;
    }

    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    public void setState( String state ) {
        this.state = state;
    }
    public String getState() {
        return this.state;
    }

    public void setZip( String zip ) {
        this.zip = zip;
    }
    public String getZip() {
        return this.zip;
    }

    public void setVip( Boolean vip ) {
        this.vip = vip;
    }
    public Boolean getVip() {
        return this.vip;
    }

    public void setBuilding( String building ) {
        this.building = building;
    }
    public String getBuilding() {
        return this.building;
    }

    public void setFailedAttempts( Integer failedAttempts ) {
        this.failedAttempts = failedAttempts;
    }
    public Integer getFailedAttempts() {
        return this.failedAttempts;
    }

    public void setActive( Boolean active ) {
        this.active = active;
    }
    public Boolean getActive() {
        return this.active;
    }

    public void setSysDomain( String sysDomain ) {
        this.sysDomain = sysDomain;
    }
    public String getSysDomain() {
        return this.sysDomain;
    }

    public void setCostCenter( String costCenter ) {
        this.costCenter = costCenter;
    }
    public String getCostCenter() {
        return this.costCenter;
    }

    public void setSysUpdatedBy( String sysUpdatedBy ) {
        this.sysUpdatedBy = sysUpdatedBy;
    }
    public String getSysUpdatedBy() {
        return this.sysUpdatedBy;
    }

    public void setSysUpdatedOn( Date sysUpdatedOn ) {
        this.sysUpdatedOn = sysUpdatedOn;
    }
    public Date getSysUpdatedOn() {
        return this.sysUpdatedOn;
    }

    public void setSysCreatedBy( String sysCreatedBy ) {
        this.sysCreatedBy = sysCreatedBy;
    }
    public String getSysCreatedBy() {
        return this.sysCreatedBy;
    }

    public void setSysCreatedOn( Date sysCreatedOn ) {
        this.sysCreatedOn = sysCreatedOn;
    }
    public Date getSysCreatedOn() {
        return this.sysCreatedOn;
    }

    public void setSysClassName( String sysClassName ) {
        this.sysClassName = sysClassName;
    }
    public String getSysClassName() {
        return this.sysClassName;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(sysId);
        sb.append("|");
        sb.append(userName);
        sb.append("|");
        sb.append(userPassword);
        sb.append("|");
        sb.append(passwordNeedsReset);
        sb.append("|");
        sb.append(preferredLanguage);
        sb.append("|");
        sb.append(country);
        sb.append("|");
        sb.append(introduction);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(middleName);
        sb.append("|");
        sb.append(lastName);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(homePhone);
        sb.append("|");
        sb.append(mobilePhone);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(lastLoginTime);
        sb.append("|");
        sb.append(lockedOut);
        sb.append("|");
        sb.append(lastPassword);
        sb.append("|");
        sb.append(manager);
        sb.append("|");
        sb.append(photo);
        sb.append("|");
        sb.append(department);
        sb.append("|");
        sb.append(company);
        sb.append("|");
        sb.append(street);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(zip);
        sb.append("|");
        sb.append(vip);
        sb.append("|");
        sb.append(building);
        sb.append("|");
        sb.append(failedAttempts);
        sb.append("|");
        sb.append(active);
        sb.append("|");
        sb.append(sysDomain);
        sb.append("|");
        sb.append(costCenter);
        sb.append("|");
        sb.append(sysUpdatedBy);
        sb.append("|");
        sb.append(sysUpdatedOn);
        sb.append("|");
        sb.append(sysCreatedBy);
        sb.append("|");
        sb.append(sysCreatedOn);
        sb.append("|");
        sb.append(sysClassName);
        return sb.toString(); 
    } 


}
